"""add source_documents to production_sample_scores

Revision ID: 3110f7ddb247
Revises: 6412377c47e5
Create Date: 2026-09-27 12:53:47.598280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3110f7ddb247'
down_revision: Union[str, Sequence[str], None] = '6412377c47e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('production_sample_scores', sa.Column('source_documents', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('production_sample_scores', 'source_documents')
    # ### end Alembic commands ###
