"""add parsing_confidence column to documents

Revision ID: 4c6edf78ba5c
Revises: 0e0c25ec1392
Create Date: 2026-09-19 22:26:08.127608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c6edf78ba5c'
down_revision: Union[str, Sequence[str], None] = '0e0c25ec1392'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('parsing_confidence', sa.String(), server_default='high', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'parsing_confidence')
    # ### end Alembic commands ###
