"""add retrieval_settings to conversation_messages and production_sample_scores

Revision ID: 77b31e276298
Revises: 3110f7ddb247
Create Date: 2026-09-27 17:02:06.691217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '77b31e276298'
down_revision: Union[str, Sequence[str], None] = '3110f7ddb247'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation_messages', sa.Column('retrieval_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('production_sample_scores', sa.Column('retrieval_settings', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('production_sample_scores', 'retrieval_settings')
    op.drop_column('conversation_messages', 'retrieval_settings')
    # ### end Alembic commands ###
