"""add duration_seconds to conversation_messages

Revision ID: f84f343bb1cb
Revises: 77b31e276298
Create Date: 2026-09-28 22:49:56.948862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f84f343bb1cb'
down_revision: Union[str, Sequence[str], None] = '77b31e276298'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation_messages', sa.Column('duration_seconds', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversation_messages', 'duration_seconds')
    # ### end Alembic commands ###
